# Generated by Django 2.2 on 2019-04-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0003_favoritebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authApi.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authApi.publishCompany'),
        ),
    ]
