# Generated by Django 2.2 on 2019-08-31 04:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0009_auto_20190716_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='payOrder',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMIntegerField(default=0)),
                ('total_price', models.DecimalField(
                    decimal_places=3, max_digits=10)),
                ('pay_type', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField(default=datetime.datetime(
                    2019, 8, 31, 4, 43, 51, 567137, tzinfo=utc))),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pay_order',
            },
        ),
        migrations.AlterField(
            model_name='shopcar',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(
                2019, 8, 31, 4, 43, 51, 566166, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='payOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('create_date', models.DateTimeField(default=datetime.datetime(
                    2019, 8, 31, 4, 43, 51, 568134, tzinfo=utc))),
                ('book', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='authApi.Book')),
                ('pay_order', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='authApi.payOrder')),
            ],
            options={
                'db_table': 'pay_order_detail',
            },
        ),
        migrations.RenameField(
            model_name='shophistory',
            old_name='transaction_total_amount',
            new_name='transaction_total_price',
        ),
        migrations.AddField(
            model_name='shophistory',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(
                2019, 8, 31, 4, 43, 51, 566166, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='shophistory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='shophistory',
            name='book',
        ),
        migrations.RemoveField(
            model_name='shophistory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='shophistory',
            name='sold_date',
        ),
        migrations.RemoveField(
            model_name='shophistory',
            name='user',
        ),
        migrations.AddField(
            model_name='shophistory',
            name='pay_order',
            field=models.ForeignKey(
                default=99999, on_delete=django.db.models.deletion.DO_NOTHING, to='authApi.payOrder'),
            preserve_default=False,
        ),
    ]
