language: python

python:
    - '3.6'

services:
    - mysql
    - redis-server

before_install:
    - python -m pip install --upgrade pip

install:
    - pip install -r requirements.txt --use-feature=2020-resolver

script:
    - python manage.py test
