# Generated by Django 2.2 on 2019-07-14 03:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190528_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 7, 14, 3, 16, 5, 286112, tzinfo=utc))),
                ('sold', models.BooleanField(default=False)),
                ('sold_date', models.DateTimeField(default=None, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shop_car',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
