# Generated by Django 2.2 on 2019-10-27 20:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190831_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='payorder',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 27, 20, 9, 15, 771307, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payorderdetail',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 27, 20, 9, 15, 772282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopcar',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 27, 20, 9, 15, 774245, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shophistory',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 27, 20, 9, 15, 775221, tzinfo=utc)),
        ),
    ]
