# Generated by Django 2.2 on 2019-10-30 01:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191028_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorder',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payorderdetail',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shopcar',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shophistory',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
