# Generated by Django 2.2 on 2020-01-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191030_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritebook',
            old_name='bookname',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='favoritebook',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='favoritebook',
            unique_together={('book', 'user')},
        ),
    ]
