# Generated by Django 2.2 on 2020-08-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_book_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcar',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
