# Generated by Django 2.2 on 2020-08-25 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200823_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTop3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_count', models.IntegerField()),
                ('count_time', models.CharField(max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Book')),
            ],
            options={
                'db_table': 'book_top3',
            },
        ),
        migrations.AddIndex(
            model_name='booktop3',
            index=models.Index(fields=['book'], name='book_top3_book_id_3c87b0_idx'),
        ),
        migrations.AddIndex(
            model_name='booktop3',
            index=models.Index(fields=['count_time'], name='book_top3_count_t_01af56_idx'),
        ),
    ]
