# Generated by Django 2.2 on 2020-09-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200825_0546'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favoritebook',
            index=models.Index(fields=['book', 'user'], name='favorite_bo_book_id_88fdc2_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthrecord',
            index=models.Index(fields=['user'], name='api_oauth_r_user_id_28aef2_idx'),
        ),
        migrations.AddIndex(
            model_name='payorderdetail',
            index=models.Index(fields=['pay_order'], name='pay_order_d_pay_ord_a22e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='shopcar',
            index=models.Index(fields=['user', 'book'], name='shop_car_user_id_fc0bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='shophistory',
            index=models.Index(fields=['pay_order'], name='shop_histor_pay_ord_69c79d_idx'),
        ),
    ]
