# Generated by Django 2.2 on 2019-04-13 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0002_auto_20190410_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='favoriteBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFavorite', models.BooleanField()),
                ('bookname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authApi.Book')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_book',
                'unique_together': {('bookname', 'username')},
            },
        ),
    ]
